# Generated by Django 3.0 on 2021-10-16 07:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 12, 30, 16, 335232), verbose_name='date published'),
        ),
    ]
