# Generated by Django 3.0 on 2021-10-16 07:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20211016_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 12, 31, 12, 165467), verbose_name='date published'),
        ),
    ]
