# Generated by Django 3.2.9 on 2021-11-24 15:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211105_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 21, 16, 3, 907202), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
