# Generated by Django 2.2.5 on 2021-12-12 06:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20211212_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='date_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 12, 12, 8, 4, 426525), verbose_name='date published'),
        ),
    ]
